spring:
  rabbitmq:
    username: admin
    password: 123456
    addresses: 192.169.1.220:5672
    cache:
      connection:
        #       缓存连接模式,默认一个连接,多个channel
        mode: channel
#        多个连接,多个channel
#        mode: connection