server:
  port: 10000 #服务注册中心端口号
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: 127.0.0.1 #服务注册中心IP地址
    prefer-ip-address: true
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/