spring:
  application:
    name: ribbon
server:
  port: 10001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
      #    自定义应用id
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@